spring:
  datasource:
    name: springbootdemo000  #数据库名
    url: jdbc:mysql://localhost:3306/springbootdemo000 #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动
